x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'

version: "3.4"

services:

  init:
    image: &tempoImage grafana/tempo:main-980437f-arm64
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo
    command: ["echo", "Tempo data directory initialized"] 

  tempo:
    image: *tempoImage # grafana/tempo:2.4.1-arm64
    command: 
      - --multitenancy.enabled=true
      - --config.file=/etc/tempo.yaml
      - --target=all
      - --storage.trace.backend=local
      - --storage.trace.local.path=/var/tempo
      - --auth.enabled=false
    volumes:
      - ./etc/tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "4317" # OTLP gRPC
      - "4318" # OTLP HTTP
      - "3200" # grafana use to query
    depends_on:
      - init
      - loki
    logging: *default-logging

  loki:
    image: grafana/loki:3.3.2-arm64
    # command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  app-a:
    # build: ./fastapi_app/
    image: ghcr.io/blueswen/fastapi-observability/app:latest
    ports:
      - "8000:8000"
    depends_on:
      - loki
    environment:
      APP_NAME: "app-a"
      OTLP_GRPC_ENDPOINT: "http://otel-collector:4317"
    logging: *default-logging

  app-b:
    # build: ./fastapi_app/
    image: ghcr.io/blueswen/fastapi-observability/app:latest
    ports:
      - "8001:8000"
    depends_on:
      - loki
    environment:
      APP_NAME: "app-b"
      OTLP_GRPC_ENDPOINT: "http://otel-collector:4317"
    logging: *default-logging

  app-c:
    # build: ./fastapi_app/
    image: ghcr.io/blueswen/fastapi-observability/app:latest
    ports:
      - "8002:8000"
    depends_on:
      - loki
    environment:
      APP_NAME: "app-c"
      OTLP_GRPC_ENDPOINT: "http://otel-collector:4317"
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9099:9099"
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
      - --web.listen-address=:9099
    depends_on:
      - loki
    logging: *default-logging

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    logging: *default-logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./etc/otelcol-contrib/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      # - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      # - 55679:55679 # zpages extension
    depends_on:
      - loki
      - tempo
      - prometheus
